# ===============================
# = BANCO DE DADOS POSTGRES
# ===============================
# Set here configurations for the database connection
spring.datasource.url=jdbc:postgresql://localhost:5433/controlefinanceiro
spring.datasource.username=postgres
spring.datasource.password=miguel123
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect