-- Para efeito de modelagem, deve-se saber que:
-- 1. Uma Despesa pode ter nenhum ou vários Empenhos.
-- 2. Um Empenho podem ter nenhum ou varios Pagamentos.
-- 3. Um Pagamento obrigatoriamente pertence a um Empenho.
-- 4. Um Empenho obrigatoriamente pertence a uma Despesa.

CREATE TABLE DESPESA
(
    ID_DESPESA        SERIAL PRIMARY KEY,
    NUMERO_PROTOCOLO  INTEGER UNIQUE NOT NULL,
    TIPO_DESPESA      VARCHAR(100)   NOT NULL,
    DATA_PROTOCOLO    DATE,
    DATA_VENCIMENTO   DATE,
    CREDOR_DESPESA    VARCHAR(255)   NOT NULL,
    DESCRICAO_DESPESA VARCHAR(255)   NOT NULL,
    VALOR_DESPESA     DECIMAL(10, 2) NOT NULL
);

CREATE TABLE EMPENHO
(
    ID_EMPENHO         SERIAL PRIMARY KEY,
    ANO_EMPENHO        INTEGER        NOT NULL,
    NUMERO_EMPENHO     INTEGER UNIQUE NOT NULL,
    DATA_EMPENHO       DATE           NOT NULL,
    VALOR_EMPENHO      NUMERIC(10, 2) NOT NULL,
    OBSERVACAO_EMPENHO VARCHAR(255)   NOT NULL,
    ID_DESPESA         INTEGER        NOT NULL,
    CONSTRAINT FK_DESPESA_EMPENHO FOREIGN KEY (ID_DESPESA) REFERENCES DESPESA (ID_DESPESA)
);

CREATE TABLE PAGAMENTO
(
    ID_PAGAMENTO         SERIAL PRIMARY KEY,
    ANO_PAGAMENTO        INTEGER        NOT NULL,
    NUMERO_PAGAMENTO     INTEGER UNIQUE NOT NULL,
    DATA_PAGAMENTO       DATE           NOT NULL,
    VALOR_PAGAMENTO      NUMERIC(10, 2) NOT NULL,
    OBSERVACAO_PAGAMENTO VARCHAR(255)   NOT NULL,
    ID_EMPENHO           INTEGER        NOT NULL,
    CONSTRAINT FK_EMPENHO_PAGAMENTO FOREIGN KEY (ID_EMPENHO) REFERENCES EMPENHO (ID_EMPENHO)
);

CREATE SEQUENCE DESPESA_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE EMPENHO_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE PAGAMENTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;